### ISSUE TITLE
Bro Ye Fix krdo yrr telegram nhi hai Mera 

### ISSUE THREAD

**Issue by MouhyiHacker** [samay825/LockIt#5]
/data/data/com.termux/files/usr/bin/hollywood, ye wla sai krdo yrr, kuch pkg nhi cal rhe

**Comment by Ghanshyamrj07** [comment]
Ss bhejo termux kaa

**Comment by samay825** [comment]
apne kuch galti kiya he maybe username and password dalne ke baad message me on instagram : sincryptzork
